services:
    monolith:
        build:
            context: ../monolith
            dockerfile: Dockerfile
        container_name: hotelio-monolith
        ports:
            - '8084:8080'
        networks:
            - hotelio-net
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
            SPRING_DATASOURCE_USERNAME: hotelio
            SPRING_DATASOURCE_PASSWORD: hotelio

    monolith-db:
        image: postgres:15
        container_name: hotelio-db
        environment:
            POSTGRES_USER: hotelio
            POSTGRES_PASSWORD: hotelio
            POSTGRES_DB: hotelio
        ports:
            - '5432:5432'
        volumes:
            - monolith-db-data:/var/lib/postgresql/data
        networks:
            - hotelio-net

volumes:
    monolith-db-data:

networks:
    hotelio-net:
        external: true
