version: v1

replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  name: booking-service
  create: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

livenessProbe:

readinessProbe:

env:
  - name: ENABLE_FEATURE_X
    value: 'false'
  - name: SERVICE_VERSION
    value: 'v1'
