# docker compose -f .delivery/configuration/booking.compose.yml up --build

services:
    booking-service:
        build:
            context: ../..
            dockerfile: .delivery/configuration/booking.dockerfile
        container_name: booking-service
        image: task2-booking-service
        ports:
            - "9090:9090"
            - "8081:8081"
        networks:
            - hotelio-net
        depends_on:
            - booking-db
        environment:
            DATABASE_URL: postgres://booking:booking@booking-db:5432/booking
            MONOLITH_BASE_URL: http://monolith:8080
    booking-db:
        image: postgres:15
        container_name: booking-db
        environment:
            POSTGRES_USER: booking
            POSTGRES_PASSWORD: booking
            POSTGRES_DB: booking
        ports:
            - "5433:5432"
        volumes:
            - booking-db-data:/var/lib/postgresql/data
        networks:
            - hotelio-net

networks:
    hotelio-net:
        external: true

volumes:
    booking-db-data:
