query GetBookingsByUser($userId: String!) {
    bookingsByUser(userId: $userId) {
        __typename
        ... on BookingsByUserSuccess {
            bookings {
                id
                userId
                hotelId
                promoCode
                discountPercent
                hotel {
                    id
                }
            }
        }
        ... on UnauthenticatedError {
            message
        }
        ... on ForbiddenError {
            message
        }
    }
}
