replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: '<request>'
    memory: '<request>'
  limits:
    cpu: '<limit>'
    memory: '<limit>'

livenessProbe:

readinessProbe:

env:
  - name: ENABLE_FEATURE_X
    value: 'false'
