replicaCount: 3

image:
  name: booking-service
  tag: latest
  pullPolicy: Never

env:
  - name: ENABLE_FEATURE_X
    value: 'false'

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
