apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{.Release.Name}}
  labels:
    app: booking-service
    version: {{.Values.version}}

spec:
  replicas: {{.Values.replicaCount}}

  selector:
    matchLabels:
      app: booking-service
      version: {{ .Values.version }}

  template:
    metadata:
      labels:
        app: booking-service
        version: {{.Values.version}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env: {{- toYaml .Values.env | nindent 12}}
          resources: {{- toYaml .Values.resources | nindent 12}}

          ports:
            - containerPort: {{.Values.service.targetPort}}

          livenessProbe:
            httpGet:
              path: /ping
              port: 8080

          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
