{{- if eq .Values.version "v2" }}
apiVersion: v1
kind: Service
metadata:
  name: booking-service-v2
  labels:
    app: booking-service
    version: v2
spec:
  type: ClusterIP
  selector:
    app: booking-service
    version: v2
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}